packages:
  - apps/*
  - packages/*
  - tools/*
  - tools/packages/*
  - packages/packages/*

cleanupUnusedCatalogs: true

catalog:
  "@types/node": 26.0.1
  vite: npm:@voidzero-dev/vite-plus-core@latest
  vitest: 4.1.9
  vite-plus: latest
  "@typescript/native-preview": 7.0.0-dev.20260626.1
  drizzle-orm: 1.0.0-rc.4
overrides:
  vite: "catalog:"
  vitest: "catalog:"
peerDependencyRules:
  allowAny:
    - vite
    - vitest
  allowedVersions:
    vite: "*"
    vitest: "*"
minimumReleaseAgeExclude:
  - "@typescript/native-preview-darwin-arm64@7.0.0-dev.20260626.1"
  - "@typescript/native-preview-darwin-x64@7.0.0-dev.20260626.1"
  - "@typescript/native-preview-linux-arm64@7.0.0-dev.20260626.1"
  - "@typescript/native-preview-linux-arm@7.0.0-dev.20260626.1"
  - "@typescript/native-preview-linux-x64@7.0.0-dev.20260626.1"
  - "@typescript/native-preview-win32-arm64@7.0.0-dev.20260626.1"
  - "@typescript/native-preview-win32-x64@7.0.0-dev.20260626.1"
  - "@typescript/native-preview@7.0.0-dev.20260626.1"
  - "drizzle-orm@1.0.0-rc.4"
allowBuilds:
  esbuild: true
  msgpackr-extract: true
catalogs:
  effect:
    effect: 4.0.0-beta.90
